replicaCount: 3

image:
  repository: asia-southeast1-docker.pkg.dev/rapid-strength-422813-t9/dbs-ui-web-app/ui-app
  tag: v0.2.0
  pullPolicy: IfNotPresent
  pullSecrets:
    - name: gcp-service-account

namespace: default

service:
  type: LoadBalancer
  port: 5000

resources:
  limits:
    cpu: 100m
    memory: 128Mi
  requests:
    cpu: 50m
    memory: 64Mi