apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: ui-blue-green-rollout
  namespace: ui-app # Adjust if your app is in a different namespace
spec:
  replicas: 3  # Adjust the number of replicas you need
  selector:
    matchLabels:
      app: ui-app  # This should match the label on your app's pods
  template:
    metadata:
      labels:
        app: ui-app
    spec:
      containers:
        - name: ui-app
          image: us-central1-docker.pkg.dev/rapid-strength-422813-t9/ui-web-app/web-app:v1.1.0
          env:
            - name: MY_POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name 
            - name: ENV_NAME
              value: "Blue"
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 5000
          livenessProbe:   # Add health checks (customize for your app)
            httpGet:
              path: /
              port: 5000
            initialDelaySeconds: 30
            periodSeconds: 10
          readinessProbe:  # Add health checks (customize for your app)
            httpGet:
              path: /health
              port: 5000
            initialDelaySeconds: 10
            periodSeconds: 10
      imagePullSecrets:
        - name: gcp-service-account 
  strategy:
    blueGreen:
      activeService: ui-app-active 
      previewService: ui-app-preview
      autoPromotionEnabled: True  # Disable automatic promotion