apiVersion: v1
kind: Service
metadata:
  name: ui-app-active
  namespace: dbs-ui-app
  labels:
    rollout.argoproj.io/revision: "active"  
spec:
  selector:
    app: ui-app    # Matches your app's pods based on their 'app' label
  ports:
    - name: http
      port: 80
      targetPort: 5000  # The port your container listens on
      protocol: TCP