apiVersion: v1
kind: Service
metadata:
  name: ui-app-preview
  namespace: dbs-ui-app
  labels:
    rollout.argoproj.io/revision: "preview"
spec:
  selector:
    app: ui-app   
  ports:
    - name: http
      port: 80  # Consider using a different port if you need to access both services directly
      targetPort: 5000
      protocol: TCP
