kind: Service
apiVersion: v1
metadata:
  name:  dbs-ui-app-svc-preview
spec:
  selector:
    app:  dbs-ui-app
  type:  ClusterIP
  ports:
  - name:  http
    port:  80
    targetPort:  8080