apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-app
  namespace: {{ .Values.namespace }} # Use namespace from values.yaml
spec:
  replicas: {{ .Values.replicaCount }}  
  selector:
    matchLabels:
      app: flask-app
  template:
    metadata:
      labels:
        app: flask-app
    spec:
      serviceAccountName: my-app-sa
      containers:
        - name: flask-app
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          env:
            - name: MY_POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
          ports:
            - containerPort: 5000
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          env:
      imagePullSecrets:
      {{- toYaml .Values.image.pullSecrets | nindent 8 }}
