apiVersion: v1
kind: Service
metadata:
  name: ui-app-service
  namespace: {{ .Values.namespace }} 
  labels:
    app: flask-app
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 5000
  selector:
    app: flask-app
